name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual trigger from GH UI

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (split per ABI)
        run: flutter build apk --release --split-per-abi --obfuscate --split-debug-info=build/debug-info/

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apk-release-${{ github.sha }}
          path: build/app/outputs/flutter-apk/*-release.apk
          retention-days: 5
